using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Circle", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Quad", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Sphere", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.HalfSphere", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cube", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Capsule", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cylinder", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cone", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Line", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes.Code.Primitives", Scope = "field", Justification = "Interop/GPU payload – requires blittable sequential fields")]

[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.DebugShapes:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.Bepu:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.Examples:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.Skyboxes:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.Windows:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.Windows:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Stride.CommunityToolkit.ImgGui:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2009:AvoidTypesWithNameTooLong", Target = "Example07_CubeClicker:Stride.Core.DataSerializers", Scope = "deep", Justification = "TODO")]

[assembly: SuppressMessage("NDepend", "ND2103:NamespaceNameShouldCorrespondToFileLocation", Target = "Example13_MeshOutline:Stride.Rendering", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2103:NamespaceNameShouldCorrespondToFileLocation", Target = "Stride.CommunityToolkit.ImGui:Stride.Rendering", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2103:NamespaceNameShouldCorrespondToFileLocation", Target = "Example13_RootRendererShader:Stride.Rendering", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2103:NamespaceNameShouldCorrespondToFileLocation", Target = "Example18_Box2DPhysics:Stride.Rendering", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2103:NamespaceNameShouldCorrespondToFileLocation", Target = "Example13_MeshOutline:Stride.Rendering", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2103:NamespaceNameShouldCorrespondToFileLocation", Target = "Stride.CommunityToolkit.DebugShapes:Stride.DebugRendering", Justification = "TODO")]
