// NDepend issue suppressions for the whole solution (NDepend reads assembly-level
// SuppressMessage attributes from any analysed assembly, so this one file covers all projects).
//
// Keep this file short. Order of preference when NDepend reports something:
//   1. fix the code;
//   2. fix the rule or the JustMyCode definition in Stride.CommunityToolkit.ndproj
//      (generated code such as Stride.Core.DataSerializers and UpdateEngineAutoGenerated
//      is excluded there, not here);
//   3. only then add a targeted suppression below, with a real justification.
//
// Target format is "AssemblyName:CodeElementFullName" - the assembly prefix is mandatory,
// wildcards are not supported. A suppression silently does nothing once its target is gone,
// so prune entries when examples are removed.

using System.Diagnostics.CodeAnalysis;

// --- Naming: entry points of languages with their own conventions --------------------------
[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Example01_Basic3DScene_FSharp:Program.main(String[])", Justification = "F# entry point is conventionally named 'main'.")]
[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Example05_PartialTorus_FSharp:Program.main(String[])", Justification = "F# entry point is conventionally named 'main'.")]
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Example01_Basic3DScene_VBasic:Example01_Basic3DScene_VBasic.Program.Main()", Justification = "VB.NET 'Main' next to the F# 'main' entry points: different language conventions, not inconsistent naming.")]

// --- DebugShapes: GPU/interop payload structs ---------------------------------------------
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Circle", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Quad", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Sphere", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.HalfSphere", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cube", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Capsule", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cylinder", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cone", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Line", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Primitives", Scope = "field", Justification = "Per-primitive vertex/index ranges filled by the mesh builders (SetupPrimitiveOffsets, BuildVertexData, BuildIndexData); plain data struct by design.")]

// --- Generated code that cannot be excluded from JustMyCode ---------------------------------
[assembly: SuppressMessage("NDepend", "ND1401:AvoidNamespacesDependencyCycles", Target = "Stride.CommunityToolkit.Examples.Launcher:Stride.CommunityToolkit.Examples.Launcher", Justification = "Avalonia-generated CompiledAvaloniaXaml.!XamlLoader instantiates App/MainWindow; not fixable in user code.")]
[assembly: SuppressMessage("NDepend", "ND1400:AvoidNamespacesMutuallyDependent", Target = "Stride.CommunityToolkit.Examples.Launcher:CompiledAvaloniaXaml", Scope = "deep", Justification = "Avalonia-generated XAML loader.")]
// --- Deliberate naming / API mirroring ---------------------------------------------------------
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Stride.CommunityToolkit.Bepu:Stride.CommunityToolkit.Bepu.SimulationExtensions", Scope = "deep", Justification = "RayCast/RayCastPenetrating mirror Stride.BepuPhysics.BepuSimulation's own casing; the Bullet wrapper mirrors Stride.Physics.Simulation.Raycast. Each wrapper matches its engine on purpose.")]
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Stride.CommunityToolkit.Bullet:Stride.CommunityToolkit.Bullet.SimulationExtensions", Scope = "deep", Justification = "Raycast/RaycastPenetrating mirror Stride.Physics.Simulation's own casing; the Bepu wrapper mirrors Stride.BepuPhysics.BepuSimulation.RayCast. Each wrapper matches its engine on purpose.")]
[assembly: SuppressMessage("NDepend", "ND3101:DontUseSystemRandomForSecurityPurposes", Target = "Stride.CommunityToolkit:Stride.CommunityToolkit.Helpers.VectorHelper", Scope = "deep", Justification = "Gameplay randomness (positions, directions); nothing security-related, and a seedable System.Random is the point.")]
