using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Example01_Basic3DScene_FSharp:Program.main(String[])", Justification = "FSharp has different convention")]

[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Program.main(String[])", Justification = "FSharp has different convention")]

[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit.ImGui:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit.Examples:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit.Bepu:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit.Bullet:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit.Skyboxes:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Stride.CommunityToolkit.Windows:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example01_Basic3DScene:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example01_Basic3DScene_FSharp:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example01_Basic3DScene_BulletPhysics:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example01_Basic3DScene_MeshLine:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example02_GiveMeACube:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example03_StrideUI_CapsuleAndWindow:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example04_MyraUI:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example05_CylinderMesh:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example07_CubeClicker:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example09_Renderer:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example10_StrideUI_DragAndDrop:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example11_ImGui:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example12_Particles:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example13_RootRendererShader:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example14_Raycast:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example15_Constraint:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Physics_Example001:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example01_Material:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example16_CollisionLayer:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example16_CollisionGroup:{anonymous namespace}", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Target = "Example_CubicleCalamity_BulletPhysics:{anonymous namespace}", Justification = "TODO")]

//[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example01_Basic3DScene_MeshLine:UpdateEngineAutoGenerated", Justification = "TODO")]

[assembly: SuppressMessage("NDepend", "ND1307:DeclareTypesInNamespaces", Scope = "deep", Target = "*", Justification = "Repository-wide decision; anonymous namespaces tolerated in examples/samples.")]

[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.ImGui:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.Examples:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.Bepu:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.Bullet:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.Skyboxes:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.Windows:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]

[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene_FSharp:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene_BulletPhysics:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene_MeshLine:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example02_GiveMeACube:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example03_StrideUI_CapsuleAndWindow:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example04_MyraUI:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example05_CylinderMesh:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example07_CubeClicker:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example09_Renderer:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example10_StrideUI_DragAndDrop:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example11_ImGui:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example12_Particles:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example13_RootRendererShader:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example14_Raycast:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example15_Constraint:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Physics_Example001:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Material:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example16_CollisionLayer:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example16_CollisionGroup:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example_CubicleCalamity_BulletPhysics:UpdateEngineAutoGenerated.UpdateMain0()", Justification = "TODO")]

[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example02_GiveMeACube:Stride.Core.DataSerializers.Example02_GiveMeACubeSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example08_DebugShapes:Stride.Core.DataSerializers.Example08_DebugShapesSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example09_Renderer:Stride.Core.DataSerializers.Example09_RendererSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example10_StrideUI_DragAndDrop:Stride.Core.DataSerializers.Example10_StrideUI_DragAndDropSerializerFactory.Initialize()", Justification = "TODO")]


[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene:Stride.Core.DataSerializers.Example01_Basic3DSceneSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene_FSharp:Stride.Core.DataSerializers.Example01_Basic3DScene_FSharpSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene_BulletPhysics:Stride.Core.DataSerializers.Example01_Basic3DScene_BulletPhysicsSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Basic3DScene_MeshLine:Stride.Core.DataSerializers.Example01_Basic3DScene_MeshLineSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example03_StrideUI_CapsuleAndWindow:Stride.Core.DataSerializers.Example03_StrideUI_CapsuleAndWindowSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example04_MyraUI:Stride.Core.DataSerializers.Example04_MyraUISerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example05_CylinderMesh:Stride.Core.DataSerializers.Example05_CylinderMeshSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example07_CubeClicker:Stride.Core.DataSerializers.Example07_CubeClickerSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:Stride.Core.DataSerializers.Example10_StrideUI_DragAndDrop_BulletPhysicsSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example11_ImGui:Stride.Core.DataSerializers.Example11_ImGuiSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example12_Particles:Stride.Core.DataSerializers.Example12_ParticlesSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example13_RootRendererShader:Stride.Core.DataSerializers.Example13_RootRendererShaderSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example14_Raycast:Stride.Core.DataSerializers.Example14_RaycastSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example15_Constraint:Stride.Core.DataSerializers.Example15_ConstraintSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example01_Material:Stride.Core.DataSerializers.Example01_MaterialSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example16_CollisionLayer:Stride.Core.DataSerializers.Example16_CollisionLayerSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example16_CollisionGroup:Stride.Core.DataSerializers.Example16_CollisionGroupSerializerFactory.Initialize()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Example_CubicleCalamity_BulletPhysics:Stride.Core.DataSerializers.Example_CubicleCalamity_BulletPhysicsSerializerFactory.Initialize()", Justification = "TODO")]




[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit.ImGui:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit.Examples:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit.Bepu:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit.Bullet:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit.Skyboxes:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Stride.CommunityToolkit.Windows:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example01_Basic3DScene:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example01_Basic3DScene_FSharp:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example01_Basic3DScene_BulletPhysics:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example01_Basic3DScene_MeshLine:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example02_GiveMeACube:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example03_StrideUI_CapsuleAndWindow:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example04_MyraUI:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example05_CylinderMesh:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example07_CubeClicker:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example09_Renderer:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example10_StrideUI_DragAndDrop:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example11_ImGui:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example12_Particles:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example13_RootRendererShader:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example14_Raycast:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example15_Constraint:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Physics_Example001:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example01_Material:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example16_CollisionLayer:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example16_CollisionGroup:UpdateEngineAutoGenerated", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND1206:AStatelessClassOrStructureMightBeTurnedIntoAStaticType", Target = "Example_CubicleCalamity_BulletPhysics:UpdateEngineAutoGenerated", Justification = "TODO")]


[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Example01_Basic3DScene_VBasic:Example01_Basic3DScene_VBasic.Program.Main()", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Example05_PartialTorus_FSharp:Program.main(String[])", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2011:AvoidFieldsWithNameTooLong", Target = "Example07_CubeClicker:Stride.Core.DataSerializers.Example07_CubeClickerCore_CubeDataSerializer.System_Collections_Generic_List_1_Example07_CubeClicker_Core_SimpleVector_Serializer", Justification = "TODO")]
[assembly: SuppressMessage("NDepend", "ND2011:AvoidFieldsWithNameTooLong", Target = "Example07_CubeClicker:Stride.Core.DataSerializers.Example07_CubeClickerCore_ClickDataSerializer.System_Collections_Generic_List_1_Example07_CubeClicker_Core_IClickable_Serializer", Justification = "TODO")]
