<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ExampleEnabled>false</ExampleEnabled>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Stride.Core" />
        <Using Include="Stride.Core.Mathematics" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Stride.CommunityToolkit\Stride.CommunityToolkit.csproj" />
    </ItemGroup>

</Project>
