// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Box2DStyleShaderKeys
    {
        public static readonly ValueParameterKey<Vector4> BaseColor = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<float> BorderThickness = ParameterKeys.NewValue<float>(0.02f);
        public static readonly ValueParameterKey<float> AntiAliasing = ParameterKeys.NewValue<float>(0.003f);
        public static readonly ValueParameterKey<int> ShapeType = ParameterKeys.NewValue<int>(0);
    }
}
