// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Example18_Box2DPhysics
{
    public static partial class Box2DPolygonSDFShaderKeys
    {
        public static readonly ValueParameterKey<Vector2> PolygonPoint0 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint1 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint2 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint3 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint4 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint5 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint6 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> PolygonPoint7 = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<int> PolygonCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<float> PolygonRadius = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> PolygonThickness = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector4> PolygonColor = ParameterKeys.NewValue<Vector4>();
    }
}
